hostname: dockerhost
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILI46QtvV7XZAMwH7zMD3PaQMPjcM9vYZhqdFvf2IKfV alexandre pitre@PC-AMD
#rancher:
#  network:
#    interfaces:
#      eth0:
#        dhcp: true
